### ISSUE TITLE
error in messages.log

### ISSUE THREAD

**Issue by skrbzr** [megahambone/FiSH#2]
ERROR 2016-12-29T19:22:49 supybot Uncaught exception in ['load'].
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/supybot/callbacks.py", line 1305, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/supybot/callbacks.py", line 1282, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/supybot/commands.py", line 1082, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/supybot/plugins/Owner/plugin.py", line 431, in load
    module = plugin.loadPluginModule(name, ignoreDeprecation)
  File "/usr/local/lib/python3.4/dist-packages/supybot/plugin.py", line 65, in loadPluginModule
    module = imp.load_module(name, *moduleInfo)
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/admin/bot/plugins/FiSH/__init__.py", line 53, in <module>
    from . import plugin
  File "/home/admin/bot/plugins/FiSH/plugin.py", line 447, in <module>
    q_dh1080 = (p_dh1080 - 1) / 2
OverflowError: integer division result too large for a float

**Comment by megahambone** [comment]
Hi there,

I run this in a python 2.7 environment, but I just merged in a pull request from @ProgVal that says the support for 3 is fixed. Give it a try now?

**Comment by ProgVal** [comment]
My PR didn't fix Python 3 support, because I can't test it. It's only a first step.

**Comment by ProgVal** [comment]
My PR didn't fix Python 3 support, because I can't test this plugin. It was only a first step.

**Comment by megahambone** [comment]
Ah, I misunderstood. I have no interest in moving my bot to Python 3 at this point, so I'll put that in the readme for now. I'll leave this open as I am looking to make some general changes to this module in the near future and will test in both 2 and 3.

**Comment by ProgVal** [comment]
If you add test cases, I can port it to Python 3
